[env:heltec-v3-pioarduino]
extends = esp32s3_base
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
board = heltec_wifi_lora_32_V3
board_build.partitions = default_8MB.csv

build_flags =
# Some CONFIG_ flags already coming from sdkconfig would also come from esp32.build_flags,
# redefining them fails the build due to "-Werror". "build_unflags" did not remove them for me,
# only option was to copy all flags here completely (minus CONFIG_*).
# begin "esp32.build_flags"
  ${arduino_base.build_flags}
#  -flto #won't work with IDF 5.5
  -Wall
  -Wextra
  -Isrc/platform/esp32
  -std=c++11
  -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DMYNEWT_VAL_BLE_HS_LOG_LVL=LOG_LEVEL_CRITICAL
  -DAXP_DEBUG_PORT=Serial
  -DESP_OPENSSL_SUPPRESS_LEGACY_WARNING
  -DSERIAL_BUFFER_SIZE=4096
  -DSERIAL_HAS_ON_RECEIVE
  -DLIBPAX_ARDUINO
  -DLIBPAX_WIFI
  -DLIBPAX_BLE
  -DHAS_UDP_MULTICAST=1
  ;-DDEBUG_HEAP
# end "esp32.build_flags"
  -mtext-section-literals # fixes "dangerous relocation" linker errors
  -D HELTEC_V3
  -I variants/esp32s3/heltec_v3_pioarduino
  -D PIOARDUINO_ESP32 # introduced here
# some PM-related debugging
  -D PowerFSMDebug
  -D DEBUG_LOOP_TIMING
# does not work with pioarduino
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER

lib_ignore =
  ${esp32_base.lib_ignore}
  libpax
  ESP RainMaker
  ESP Insights

custom_sdkconfig = file://variants/esp32s3/heltec_v3_pioarduino/sdkconfig.heltec-v3-pioarduino

custom_component_remove = espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp_diagnostics
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3
                          espressif/lan867x
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/fb_gfx
                          espressif/lan86xx_common

