# Disable WIFI alltogether to save memory 
[env:tlora-v2-1-1_6_nowifi]
extends = esp32_base
board = ttgo-lora32-v21
board_check = true
build_flags =
  ${esp32_base.build_flags} -D TLORA_V2_1_16 -I variants/esp32/tlora_v2_1_16
   -D MESHTASTIC_EXCLUDE_GPS=1
   -D MESHTASTIC_EXCLUDE_AUDIO=1
   -D MESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
   -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
   -D MESHTASTIC_EXCLUDE_ATAK=1
   -D MESHTASTIC_EXCLUDE_POWERSTRESS=1
   -D MESHTASTIC_EXCLUDE_WIFI=1
   -D MESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
   -DBUTTON_PIN=12

lib_ignore =
  libpax
  Wifi

upload_speed = 921600
