[env:heltec-v4-lp]
extends = heltec_v4_base
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

custom_sdkconfig =
  CONFIG_PM_ENABLE=y
  CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
  CONFIG_BT_NIMBLE_ENABLED=y
  CONFIG_ESP_SLEEP_GPIO_RESET_WORKAROUND=y
  CONFIG_PM_SLP_DISABLE_GPIO=y
#  CONFIG_PM_SLP_IRAM_OPT=y
  CONFIG_BT_CTRL_MODEM_SLEEP=y
  CONFIG_BT_CTRL_MODEM_SLEEP_MODE_1=y
  CONFIG_BT_CTRL_LPCLK_SEL_EXT_32K_XTAL=y
# from esp32.ini
  CONFIG_BT_NIMBLE_MAX_BONDS=6
  CONFIG_NIMBLE_CPP_LOG_LEVEL=2
  CONFIG_BT_NIMBLE_MAX_CCCDS=20
  CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
  CONFIG_AUTOSTART_ARDUINO=y
# Meshtastic uses old API, TODO
  CONFIG_ADC_SUPPRESS_DEPRECATE_WARN=y
  CONFIG_ADC_SKIP_LEGACY_CONFLICT_CHECK=y
  CONFIG_PM_DFS_INIT_AUTO=y

# via custom_sdkconfig, do not redefine. does not work, see below
build_unflags = 
  -DCONFIG_BT_NIMBLE_MAX_BONDS=6
  -DCONFIG_NIMBLE_CPP_LOG_LEVEL=2
  -DCONFIG_BT_NIMBLE_MAX_CCCDS=20
  -DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192

build_flags = 
# repeat all inherited minus the "excluded" ones as build_unflags does not work...
  ${arduino_base.build_flags}
#  -flto  #https://community.platformio.org/t/import-arduino-lilygo-t-deck-project/47863
  -Wall
  -Wextra
  -Isrc/platform/esp32
  -std=c++11
  -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DMYNEWT_VAL_BLE_HS_LOG_LVL=LOG_LEVEL_CRITICAL
  -DAXP_DEBUG_PORT=Serial
  -DESP_OPENSSL_SUPPRESS_LEGACY_WARNING
  -DSERIAL_BUFFER_SIZE=4096
  -DSERIAL_HAS_ON_RECEIVE
#  -DLIBPAX_ARDUINO
#  -DLIBPAX_WIFI
#  -DLIBPAX_BLE
  -DHAS_UDP_MULTICAST=1
  -DBUTTON_THREAD_INTERVAL_MS=100
# ..and ours
  -D PIOARDUINO_ESP32 # introduced here
  -D HELTEC_V4
  -I variants/esp32s3/heltec_v4_lp
  -D HELTEC_V4_OLED
  -D USE_SSD1306 ; Heltec_v4 has an SSD1315 display (compatible with SSD1306 driver)
  -D LED_PIN=35
  -D RESET_OLED=21
  -D I2C_SDA=17
  -D I2C_SCL=18
  -D I2C_SDA1=4
  -D I2C_SCL1=3
  -D PowerFSMDebug
  -D DEBUG_LOOP_TIMING
# does not like pioarduino?
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER
# Issue with "dangerous relocation: l32r: literal placed after use: (.literal._ZN15SX126xInterfaceI6SX1262E16disableInterruptEv+0x8)"
# https://docs.espressif.com/projects/esp-idf/en/v5.4/esp32c3/api-guides/memory-types.html#how-to-place-code-in-iram
  -fno-tree-switch-conversion
  -mlongcalls
  -mtext-section-literals

lib_ignore =
  ${esp32_base.lib_ignore}
  libpax
  ESP RainMaker
  ESP Insights

custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

lib_deps = 
  ${heltec_v4_base.lib_deps}

